version: '3.8'

services:
  app:
    image: thetombrider/personal-finance:latest
    container_name: fintrack
    ports:
      - "5001:5000"
    env_file: stack.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - db
    restart: always
    networks:
      - cloudflare_network # To talk to the Tunnel
      - internal_finance   # To talk to the DB

  db:
    image: postgres:15-alpine
    env_file: stack.env
    volumes:
      - personal_finance_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    networks:
      - internal_finance



volumes:
  personal_finance_postgres_data:

networks:
  cloudflare_network:
    external: true
  internal_finance:
    driver: bridge
